services:
  postgres:
    image: postgres:16
    container_name: wow-raid-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5690:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wow-raid-network

  adminer:
    image: adminer:latest
    container_name: wow-raid-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - wow-raid-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  wow-raid-network:
    driver: bridge
